<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OCNSY-23" failures="2" tests="2" name="cucumber.learn.runner.Runner" time="0.234" errors="0" timestamp="2025-03-24T18:29:26 IST" skipped="0">
  <testcase classname="cucumber.learn.runner.Runner" name="runScenario" time="0.019">
    <failure message="manaully throw some error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: manaully throw some error
at org.testng.Assert.fail(Assert.java:111)
at cucumber.learn.stepDefinitions.LoginStepDefinition.click_the_submit_button(LoginStepDefinition.java:35)
at ✽.click the submit button(file:///D:/STUDENTS/Testing-Jan-2025/cucumber.learn/src/test/resources/features/login.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="cucumber.learn.runner.Runner" name="runScenario" time="0.215">
    <failure message="manaully throw some error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: manaully throw some error
at org.testng.Assert.fail(Assert.java:111)
at cucumber.learn.stepDefinitions.LoginStepDefinition.click_the_submit_button(LoginStepDefinition.java:35)
at ✽.click the submit button(file:///D:/STUDENTS/Testing-Jan-2025/cucumber.learn/src/test/resources/features/login.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- cucumber.learn.runner.Runner -->
